name: Deploy HTML and PDF slides to Pages

on:
  # Runs after HTML deployment
  workflow_run:
    workflows: [Deploy HTML slides to Pages]
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  pages-pdf:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/pages.yml
    with:
      include_pdf: true
